spring.application.name=cooking_book
spring.datasource.url=jdbc:postgresql://localhost:32768/db
spring.datasource.username=rootuser
spring.datasource.password=rootpass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
server.port=8080
